version: '3.8'
services:
  frontend:
    depends_on:
      - anvil
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  anvil:
    build:
      context: ./smartcontracts
      dockerfile: Dockerfile.anvil
    ports:
      - 8545:8545

  deploy:
    depends_on:
      - anvil
    build:
      context: ./smartcontracts
      dockerfile: Dockerfile.deploy